# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 107b1612226df4b001614a4839645e32ffe8243f0822f9cb87a45a7aed76c78edb51951f9b0a1b12abfcb5b8a4b38d4fa7e3ae7f942e661d975bfea50f4b88f6

test:
  secret_key_base: 64562684f6b6e99709fe2ae2177920963e42757b2d5df657df152106195ea1c5bf32de0f7eeb7b951a47591ffc75dbfb3134f856dc44e90ef14204758e8be347

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
